### ISSUE TITLE
Section 5.2 title

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/openintro-statistics#30]
Section 5.2 is titled CONFIDENCE INTERVALS FOR A SAMPLE PROPORTION, but I think it should be CONFIDENCE INTERVALS FOR A PROPORTION since the CI is for the population parameter. This would also match the title of the next section on hypothesis testing.

**Comment by OpenIntroOrg** [comment]
Thanks! This has now been fixed on Github and in the released PDFs.
