### ISSUE TITLE
Exercise 4.14

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/openintro-statistics#37]
book → os
feedback_type → textbook_typo_exercise
textbook_page → 148
feedback_name → Neely Atkinson
feedback_email → enatk@rice.edu

feedback
Exercise 4.14 c). The example is a geometric distribution with p=0.02. The question asks how many failures are expected before the first success. The Answer Key gives 1/p = 50. I believe this is the expected number of the trial on which the first success occurs. The expected number of failures is therefore 49. This may be related to the fact that the text and R define the geometric distribution (and the negative distribution as well) differently.) My apologies if this is not correct.

**Comment by OpenIntroOrg** [comment]
This has now been fixed in the exercise bank, so it will get captured going forward.
