### ISSUE TITLE
Problem 4.37 University Admissions wrong solution

### ISSUE THREAD

**Issue by alfredzou** [OpenIntroStat/openintro-statistics#41]
Version: 4

I think the answer is wrong for this question (5.59% with a 0.5 correction), could you please check.

I calculated a probability of 6.06% with a 0.5 correction.

![image](https://user-images.githubusercontent.com/53513690/91931373-9dc9a700-ed26-11ea-81b5-94d77790a75b.png)

I confirmed this with this [calculator ](https://mathcracker.com/normal-approximation-binomial-distribution)

![image](https://user-images.githubusercontent.com/53513690/91930977-92c24700-ed25-11ea-989a-d48fb2883d1a.png)

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the question! 

The solution is calculated for (P >= 1787) since if there are exactly 1786 students, everyone would get a spot. But one more, and someone is out of a place. (1787-1750)/23 = 1.608696 -> 1.61.

**Comment by alfredzou** [comment]
Thanks Mine! That makes a lot of sense.

I think the answer would be clearer if it was phrased: 
Want to find the probability that there will be <s>1,786</s> 1,787 or more enrollees.

p.s. I've just finished the first course of Coursera's Statistics with R and I really enjoyed it!

**Comment by mine-cetinkaya-rundel** [comment]
@alfredzou Definitely, I'll update the language for the next edition.

And glad you enjoyed the course!

**Comment by DavidDiez** [comment]
Thanks Alfred for reporting! I've now added the solution typo you noted to the typos spreadsheet (linked from openintro.org/book/os) with a Thank You to you.
